# Generated by Django 3.2.9 on 2021-11-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('User_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=25)),
                ('Last_Name', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=50)),
                ('State', models.CharField(blank=True, max_length=25)),
                ('City', models.CharField(blank=True, max_length=25)),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('Zip_Code', models.IntegerField(blank=True, null=True)),
                ('Phone_Number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('User_Id',),
            },
        ),
    ]
