# Generated by Django 3.2.9 on 2021-11-08 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('Brand_Id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Brand_Name', models.CharField(max_length=50)),
                ('Rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ('Brand_Id',),
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('User_Name',)},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_Id',
            new_name='User_Name',
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('Seller_Id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('State', models.CharField(blank=True, max_length=25)),
                ('City', models.CharField(blank=True, max_length=25)),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('Zip_Code', models.IntegerField(blank=True, null=True)),
                ('Phone_Number', models.IntegerField(blank=True, null=True)),
                ('Brand_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.brand')),
            ],
            options={
                'ordering': ('Seller_Id',),
            },
        ),
    ]
