# Generated by Django 3.2.9 on 2021-11-08 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20211107_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='Brand_Id',
            field=models.ForeignKey(db_column='Brand_Id', on_delete=django.db.models.deletion.CASCADE, to='Products.brand'),
        ),
    ]
