# Generated by Django 3.2.9 on 2021-11-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_product_info_product_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_info',
            options={'ordering': ('Product_Id',)},
        ),
    ]
