# Generated by Django 3.2.9 on 2021-11-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_product_info_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='nutrition_table',
            fields=[
                ('Product_Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Calories', models.FloatField(blank=True, null=True)),
                ('Total_Fat', models.FloatField(blank=True, null=True)),
                ('Saturated_Fat', models.FloatField(blank=True, null=True)),
                ('Transfat', models.FloatField(blank=True, null=True)),
                ('Cholesterol', models.FloatField(blank=True, null=True)),
                ('Sodium', models.FloatField(blank=True, null=True)),
                ('Total_Carbohydrate', models.FloatField(blank=True, null=True)),
                ('Protein', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ('Product_Name',),
            },
        ),
        migrations.AlterField(
            model_name='product_info',
            name='Image',
            field=models.URLField(blank=True),
        ),
    ]
