# Generated by Django 3.2.9 on 2021-11-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20211108_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_info',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
