# Generated by Django 3.2.9 on 2021-11-08 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_test_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('Recipe_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Source_Url', models.URLField(blank=True, null=True)),
                ('Title', models.CharField(max_length=100, null=True)),
                ('Instruction', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('Recipe_Id',),
            },
        ),
        migrations.CreateModel(
            name='recipe_ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingredient', models.CharField(max_length=50)),
                ('Recipe_Id', models.ForeignKey(db_column='Recipe_Id', on_delete=django.db.models.deletion.CASCADE, to='Products.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='recipe_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Recipe_Id', models.ForeignKey(db_column='Recipe_Id', on_delete=django.db.models.deletion.CASCADE, to='Products.recipe')),
            ],
        ),
    ]
