# Generated by Django 3.2.9 on 2021-11-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_product_info_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition_table',
            name='Product_Name',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
