# Generated by Django 3.2.9 on 2021-11-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_nutrition_table_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_images',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
