# Generated by Django 3.2.9 on 2021-11-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_nutrition_table_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_images',
            name='id',
        ),
        migrations.AddField(
            model_name='recipe_images',
            name='Id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
