# Generated by Django 3.2.9 on 2021-11-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_nutrition_table_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanted_item',
            name='Valid',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
