# Generated by Django 3.2.9 on 2021-11-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_nutrition_table_product_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wanted_item',
            unique_together=set(),
        ),
    ]
