# Generated by Django 3.2.9 on 2021-11-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_recipe_images_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe_ingredients',
            name='Ingredient',
            field=models.CharField(max_length=250),
        ),
    ]
