# Generated by Django 3.2.9 on 2021-11-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20211126_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='Phone_Number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Phone_Number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
